# Generated by Django 5.0.2 on 2024-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_randomcitydata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomcitydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
