# Generated by Django 5.0.2 on 2024-03-07 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_alter_randomcitydata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcitydata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
